---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    storageClass: ceph-block
    size: 5Gi
  primaryUpdateStrategy: unsupervised
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      memory: "2Gi"
  superuserSecret:
    name: postgres-cluster-secret