---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2"
stores:
  yaml:
    indent: 2
