apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+QHsN6Oqarh8X98KYR77RZb5PhxTRkRnZXCKJXV+LKwoC1o5McbPSQ==,iv:ImU6fnPh61ijg0NJclnIymxjItddCdq7iOZuU3LkWOU=,tag:G2a4ilQdQjOjmtYME+wXzA==,type:str]
sops:
  age:
    - recipient: age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUnNRTG1YUkVrcjRNWGI4
        czZLT3hhTkdNYkFRQzloTnpDU1ozNC92c0M0CkRCekhtMDdjblBlOWNhZmEyTnQz
        anRmUE82RmRiM0ZiTU1KRTNwenBNVncKLS0tIEgzcFh1UExlNnlQV1VWVUNJbW1h
        QTdCTi9OaW9GeXZjeGYrMVdxY1B4bzQK3ambQ6uzzuaXLHuTWT/S8+vsS7c5ocSF
        7FOqw23cPlJMR65zUvoINBoPE9TRfek7cCsv73EehqViwSETe0pOJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:35:18Z"
  mac: ENC[AES256_GCM,data:jMDJ2wgIJfZmiWEaZhEdPvPWTrBEgqLUqTVUY05xdFYvR5UNWx5cDdYjDD7zAJbrEDKTF0akq/WXPQ5C76gHtUweCulYUVt1XNOuIHIq8cpqkUyJ7RBXHz2EPjePfF6ch1ampz/blE7BqDOtN+RBjEjN9p3hZGAy+p00VPrFfGw=,iv:0Qv08x9hZF9vpfsPZACtxFQ9Q1axt3t4h82UaM775C4=,tag:8yNidoOYYBp3UmzuHZuD7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
