apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:s5iQZ+0wUDUNGg3k,iv:Rdm+/N4GTTkfke0z20yAB5Yk02N1UPBti1RbtD0hZ+Y=,tag:1LgPKXybrnWxdKvvxmrjow==,type:str]
sops:
  age:
    - recipient: age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c3JRcDRXY25kMlljWGY3
        RG9qdFZoSXRHWUI2YTVFL05SVy9MZGpsU1IwCnhNSWdkaG1aQWw4NXJNK2FyZDg1
        dHpHZWE5bElWRVp4Z3FkWWJWVkpaT2cKLS0tIHoxYmxnSE5LYmJkLzFaVSthYmlq
        Q1BSUFdsM2VNNHUwSWxwL2lFcVBmNlUKp7QzJEIHMpFC291mOMF7yM7kVZaCqljy
        fwxWA8Pdx6MOmyRIIjlRFAbsZbOuuh+22G4IxBaZex9EI05QM2SSPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:35:18Z"
  mac: ENC[AES256_GCM,data:vMDP9fppvpr76lAnfcNUg/mp3gGJxUCigcRSU29N0+r+YS3bQTwUnNTu2TbfY6kluOTJIaJY/0i8d5dk/O5c17IFmddPtDknIPyL9jQ8OnmrWPBmWfXhAX7RfQkVlcq1CODlu9pKp+QaOPtJiiQPcxpMj2VFabh3Rn27z5r5oig=,iv:56f9nxfTVOulAfXKzh27aoZ2jPu6SZCdiAmwZ2xksHU=,tag:avX2snF5zGlA9UXuKiQZCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
