apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QF6NxmBzPmvysR9Pmbx4WYuS7JfwZ+uhtgYFtYDRz7Q=,iv:0xZchq82u+c1tT46zzQh6WwuyigJmouDC/ljY+8A1nI=,tag:MSfP7OJrlasjcPJcUivt7Q==,type:str]
sops:
  age:
    - recipient: age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTStzU2JsZTUyZldFUjNz
        VkhwcGxybVkwVm9EVU9IajVBOGc5dHdSdUR3Cis1TVdYcW4xYUNKcmNJWEMzOCtI
        VFlFYnpOdWpLQ3JHeEkyWUk5RTZOTm8KLS0tIGVyQUhBWGV0LzU4akd6aEVpNS90
        NTh6N282UXhsQ3hPb2ZlK3o4K2d2TXcKlHLYawyGtan7UewOtW3hDgP4SCdK36GY
        tzEaDCqVfdr9GXCQJsyoQxD9WSc7yhXNT3Oz3acTfdabA4uJ+4MmCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:35:18Z"
  mac: ENC[AES256_GCM,data:ozIOpgdhUGyv/UJhGwz7p7/lncFkdYC7xSAKKn+/73mJaiCcnZvOiHz2h+MgsFHx7tsmcdQAPdBSEvV7Dk/VzyMD6iBa4d70Zu8zvplBmTbBGTChaBrCdFxDj38rcVgdRgHedDHsa/hCjQvcfmm14EkVbCxwyZoVM+2UjuzeVVo=,iv:Ho+3XNgj6BbqBvbvwn3F1YjM2E6YFYalWQ9vOwpPv4E=,tag:daoRdidoAC1iJyAajNCkrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
