---
apiVersion: apiserver.config.k8s.io/v1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://auth.fade-lab.com/application/o/kubernetes/
      audiences:
        - kubernetes
    claimMappings:
      username:
        claim: preferred_username
      groups:
        claim: groups