---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik
    template:
      data:
        secret-key: "{{ .SECRET_KEY }}"
        postgres-password: "{{ .PG_PASS }}"
  dataFrom:
    - extract:
        key: authentik
