---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        secret_key: "{{ .SECRET_KEY }}"
  dataFrom:
    - extract:
        key: authentik
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-db
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .PG_PASS }}"
  dataFrom:
    - extract:
        key: authentik
