---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  chart:
    spec:
      chart: *app
      version: 2026.5.6
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 30m
  values:
    authentik:
      postgresql:
        host: postgres-rw.database.svc.cluster.local
      redis:
        host: authentik-dragonfly
        db: 1
        port: 6379

    blueprints:
      configMaps:
        - authentik-blueprints

    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secret

    postgresql:
      enabled: false
    redis:
      enabled: false

    server:
      env:
        - name: GRAFANA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-grafana-secret
              key: GRAFANA_CLIENT_SECRET
        - name: HARBOR_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-harbor-secret
              key: HARBOR_CLIENT_SECRET
        - name: FLUX_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-flux-secret
              key: FLUX_CLIENT_SECRET

    worker:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      env:
        - name: GRAFANA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-grafana-secret
              key: GRAFANA_CLIENT_SECRET
        - name: HARBOR_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-harbor-secret
              key: HARBOR_CLIENT_SECRET
        - name: FLUX_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentik-flux-secret
              key: FLUX_CLIENT_SECRET
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 30
        timeoutSeconds: 30
        failureThreshold: 5
      readinessProbe:
        initialDelaySeconds: 120
        periodSeconds: 30
        timeoutSeconds: 30
        failureThreshold: 5
      startupProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 30
        failureThreshold: 30
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 750m
          memory: 1Gi
    prometheus:
      rules:
        enabled: true #