---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  chart:
    spec:
      chart: *app
      version: 2026.5.6
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 30m
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: pg_password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secret
      valuesKey: secret_key
      targetPath: authentik.secret_key
  values:
    authentik:
        postgresql:
            host: postgres-rw.database.svc.cluster.local
    server:
      volumes:
        - name: blueprints
          configMap:
            name: authentik-blueprints

    volumeMounts:
      - name: blueprints
        mountPath: /blueprints/custom

    postgresql:
        enabled: false