---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-secret
    template:
      data:
        CODER_PG_CONNECTION_URL: "postgres://coder:coder@postgres-rw.database.svc.cluster.local:5432/coder?sslmode=disable"
        PG_PASSWORD: "{{ .PG_PASS }}"
  dataFrom:
    - extract:
        key: coder
