---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  chartRef:
    kind: OCIRepository
    name: coder
  interval: 1h
  values:
    env:
      - name: CODER_ACCESS_URL
        value: "https://coder.${SECRET_DOMAIN}"
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_PG_CONNECTION_URL
      - name: CODER_OIDC_ISSUER_URL
        value: https://auth.${SECRET_DOMAIN}/application/o/coder
      - name: CODER_OIDC_CLIENT_ID
        value: coder
      - name: CODER_OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CLIENT_SECRET
    envUseClusterAccessURL: false