apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ss2XE43vxOynFEiNfTSoPoHxHetDDtpNGd91avL8tTw5TwP75YK16zGpG+TeR0PcrZRrof2Us8uvt3hXto30I6UwzBPgGB3h3f6EainZSqlmRgst74NLdViM2wVCvKm0RQ/CaVT8D3BP0eqWkcdXEiYEwt3BWJP2YY3uEPb5D8UGHHRs8vD0O2zQDkcnI3AleOdk/3NgTPPL88z6SG3izyf5OmjFMKabBnUOL3JTrB32nlQC,iv:hUZjh65eIxbjqF5KbQr/2552+ZvCkdTTG272iCuCNQ4=,tag:EjnEJ1Aw/x5g/C4uAgzhTg==,type:str]
sops:
  age:
    - recipient: age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRDFZU1NOL2NnSExLempM
        VmRtMDFhVkNLcnNxdEIwK28zalU2eng4V1dNCkN0aHA1a1N2OHRCMTk4enkyejk0
        Qkx0bndaSmkyUjUxcUVWYys2UGRITjQKLS0tIGRwSHoxL0thelBYTFM1elh5UkZE
        bzM1ZnJsQ3hldFVPVlAwWGE3ckkvMkEKALACTuJqu/TwsLRgiseSWp5rgjI3cM3q
        feoQ+Vq5UC6Ai1McBZkdKFNh0MjL+6ARw1mndQfTBsVM+ztT7s2lZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:35:18Z"
  mac: ENC[AES256_GCM,data:MO0NWb5nhu19thrQ8MKr1/Mh8J+jqj4YKJBk0B6PzSYKGZySpIxvMc5nJZQ6pMiWpIgc9L2Zq4Z4K/+flW4fsLYt02WyaufIKGDq+MxsD8F+77x3yf9kqOE1DuXEHqYPObhd1P68v7J7NhkEteyTkPc1hcZCpJoCWAuIQqfgJXI=,iv:/q2H1b1HxQcF69w4/s/xHaVrOBaCdBfG6N2YQsrRnf4=,tag:F9jLaev1TgMkIB1oFtOsPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
