---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rancher
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: rancher
  interval: 1h
  path: ./kubernetes/apps/observability/rancher/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
