---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chartRef:
    kind: OCIRepository
    name: headlamp
  interval: 30m
  values:
    fullnameOverride: headlamp
    config:
      oidc:
        secret:
          create: false
        clientID: headlamp
        clientSecret: "BGBXO96t6czTIHtNnW5UxoGqsbFuzIdsyGpyMBiAJB3eqJbLHEB8vbRi3r41bw9aVT0FWin8K17fvPbP4aDh2KxMRIG63OpWvCXzwwaWIZWwWYSzWPxOlqpsxCaIsoDv"
        issuerURL: "https://auth.fade-lab.com/application/o/headlamp/"
        scopes: "openid,email,profile,groups"
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      port: 4466