apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:HFlIZorhHsNzrm45AaxcdCQfkErw5gMxatAbIfkZsesx1OwRX/hsjA==,iv:FHlvuZmOIAOBXhadmb8GSAeyEJBOTnUUbQ1f54uLQMQ=,tag:g8/+7hw+56bII/CFZ2izlg==,type:str]
sops:
  age:
    - recipient: age190tln2h8qcs0qam9vqfh8playmtna4tlcf8ja5kyu67c70lslykqmhk2t2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUjJIaEc1cEZXWWtmaEFB
        TFRRY2FBS0JJNEt2eEp3QUlKSjM3SUdiZkVnCkZXOW5OOGpyMzZWcjY0clZYdkho
        b2NOZ1g4aUJpZjVQcWxha210NGx4amsKLS0tIDYySnJDa0tQQ1l0dWloVW1XMklP
        MVBLU0FtSDNGUVVCMDZIQnI3MEVIbGsK5t+uGNfZPaoL0/S89L5kCnQpFZD9OqBx
        /XyKMSFxWtaOnf0h9+lr4dHZ7zOh7ZIjb/i8uYppSGacvIjD2VIunA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:35:18Z"
  mac: ENC[AES256_GCM,data:1u1llVzNQDKC+bV8BuoBZQp35vBFsGpcclQN/mGgVsrdshXcT+SformxFoW+mDfM4vEHVtumi8HwTCxnUMNw72yrVg0jhy3mB1l6u4RaLNsmenxWqztQbbAsU/1yD7KlPuoxALzJlerPoNqeT5jUfzXG0KMcoseXTjoVuNWaICE=,iv:NBQzV4wcGlrVlT+AxMsf7vxZMsS7KgcTCZa8+IZEPBA=,tag:Xw+kUmKydpIk7Rdw/+ohvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
