# yaml-language-server: $schema=https://kube-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.39.0
  replicas: 3
  networkPolicyEnabled: false
  args:
    - --maxmemory=2560Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 3Gi